apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: myargo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Durbace/TechTrekLogAnalyzer.git
    targetRevision: HEAD
    path: k8s
  destionation:
    server: https://kubernetes.default.svc
    namespace: myproject

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
