apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-project-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-project
  template:
    metadata:
      labels:
        app: kube-project
    spec:
      containers:
      - name: kube-project
        image: botfluti/project:2.0
        ports:
        - containerPort: 80

